# Ce fichier de configuration permet de personnaliser l'installation

#Configuration Apache
#ConfigurationFile correspond à l'adresse du fichier modèle de configuration
#ServerName correspond au nom du domaine
#ServerAdmin correspond à l'adresse email de l'administrateur du site
#DocumentConfName correspond au nom du fichier de configuration qui sera utilisé
#DocumentRoot correpond à l'adresse des fichiers Wordpress
apache:
    configurationFile : "configuration_files/apache.example.com.conf"
    ServerName: "example.com"
    ServerAlias: "www.example.com"
    ServerAdmin: "admin@example.com"
    DocumentConfName : "wordpress.conf"
    DocumentRoot: "/var/www/html/wordpress"
    paquets: 
        - 'apache2'

#rootPassword correspond au mot de passe root de la base de données à créer
#wordpressDbName correspond au nom de la base de données Wordpress qui sera créée
#wordpressUser correspond au login pour se connecter à la base de données Wordpress
#wordpressUserPassword correspond au mot de passe pour se connecter à la base de données Wordpress
sql:
    rootPassword: "root"
    wordpressDbName: "wordpress"
    wordpressUser: "wpuser"
    wordpressUserPassword: "wp-password"
    paquets: 
        - 'mariadb-server'
        - 'mariadb-client'

#url correspond à l'adresse de récupération de l'archive contenant le dossier Wordpress
#tempDir correspond à l'adresse de téléchargement du fichier sur votre serveur
wordpress:
    url: "https://wordpress.org/latest.tar.gz"
    fileName: "latest.tar.gz"
    tempDir: "/tmp"
    
php:
    paquets: 
        - 'php7.2'
        - 'libapache2-mod-php7.2'
        - 'php7.2-common'
        - 'php7.2-mbstring'
        - 'php7.2-xmlrpc'
        - 'php7.2-soap'
        - 'php7.2-gd'
        - 'php7.2-xml'
        - 'php7.2-intl'
        - 'php7.2-mysql'
        - 'php7.2-cli'
        - 'php7.2-zip'
        - 'php7.2-curl'